### ISSUE TITLE
Keeping Up with LinkedIn DustJS

### ISSUE THREAD

**Issue by neilchaudhuri** [jmparsons/sbt-dustjs-linkedin#3]
Clearly there has been no need for updates to the plugin, but is there a way to make sure the improvements to the core LinkedIn DustJS library are incorporated into the plugin?

Thanks.

**Comment by jmparsons** [comment]
@neilchaudhuri I'll look into updating the plugin and will double check with core for updates.

**Comment by efrister** [comment]
+1

**Comment by jmparsons** [comment]
@neilchaudhuri @efrister To use the latest dustjs override the version used to compile by adding the dependency in `project/plugins.sbt`:

    addSbtPlugin("com.jmparsons.sbt" % "sbt-dustjs-linkedin" % "1.0.3")

    libraryDependencies += "org.webjars" % "dustjs-linkedin" % "2.6.1-1"

Then match it up on your project by updating your `build.sbt`

    libraryDependencies ++= Seq(
      "org.webjars" % "dustjs-linkedin" % "2.6.1-1"
    )

If you clean your project and remove the generated `target/project` folder, doing a search for 'v2.6' should show the results using the newer dust and not of 'v2.4'.

Let me know if that works. The webjars might need newer versions as well.

**Comment by jmparsons** [comment]
This project has been updated. c758c01c1fd338b7b8eda20b0044bc287bcaf17b
