### ISSUE TITLE
Incorrect Link to Dust on Webjars

### ISSUE THREAD

**Issue by neilchaudhuri** [jmparsons/sbt-dustjs-linkedin#4]
I have the plugin like so in build.sbt:

 "org.webjars" % "dustjs-linkedin" % "2.6.1"

The result is to look for Dust here:

http://cdn.jsdelivr.net/webjars/dustjs-linkedin/2.6.1/dust-core.min.js

This leads to a 504.

However, Dust is actually here:

http://cdn.jsdelivr.net/dustjs/2.6.1/dust-core.min.js

Am I doing something wrong in the way I've set things up? I have found this is a fairly recent development, but I can't place exactly when.

**Comment by jmparsons** [comment]
@neilchaudhuri both links work for me. The first doesn't 504. Is it still going to a 504 for you?

**Comment by neilchaudhuri** [comment]
Confirmed things are back to normal. Must have been a glitch in the CDN. Thanks for your help.
